---
title: "R Notebook"
output: html_notebook
---

This is for how to create great visualizations in R for clstering

```{r}
#Loading Data

data("USArrests")

#compute dissimilarity matrix

dd <- dist(scale(USArrests), method = "euclidean")

#Hierarchial Clustering

hc <- hclust(dd, method = "ward.D2")

#hang put labels at same height
plot(hc, hang = -1, cex = 0.6)


```

```{r}
#Dendrogram 

hcd <- as.dendrogram(hc)

plot(hcd, type = "rectangle", ylab = "Height")

plot(hcd, type = "triangle", ylab = "Height")

#Customizing hcd plot

nodepar <- list(lab.cex = 0.6, pch = c(NA, 19), cex = 0.7, col = "blue")

plot(hcd, ylab = "Height", nodePar = nodepar, leaflab = "none", edgePar = list(col = 2:3, lwd = 2:1))

#if we write horiz = TRUW then plot will be horizontal
#edgepar to change color of branches


```

```{r}
#Phylogenetic Trees

library(ape)

plot(as.phylo(hc), cex = 0.6, type = "fan", label.offset = 0.5)
#Type can be cladogram, unrooted, fan, radial or phylogram : default is phylogram

#cut dendrogram into 4 clusters
colors = c("red", "blue", "green", "black")
clus4 = cutree(hc,4)
plot(as.phylo(hc), type = "fan", tip.color = colors[clus4], label.offset = 1, cex = 0.7)


plot(as.phylo(hc), type = "cladogram", cex = 0.6,
     edge.color = "steelblue", edge.width = 2, edge.lty = 2,
     tip.color = "steelblue")

```

```{r}
library(ggdendro)
library(ggplot2)

ggdendrogram(hc, theme_dendro = FALSE)

dend <- as.dendrogram(hc)
dend_data <- dendro_data(dend, type = "rectangle")
names(dend_data)

ggplot(dend_data$segments) + geom_segment(aes(x=x,y=y,xend=xend,yend=yend)) +
  geom_text(data = dend_data$labels, aes(x,y,label = label), hjust=1, angle=90, size =3) + ylim(-3,15)
```
```{r}
#Dendextend

library(dendextend)

dend <- USArrests[1:5,] %>% # data
        scale %>% # Scale the data
        dist %>% # calculate a distance matrix, 
        hclust(method = "ward.D2") %>% # Hierarchical clustering 
        as.dendrogram # Turn the object into a dendrogram.
plot(dend)

dend %>% set("labels_col", value = c("green", "blue"), k=2) %>% 
          plot(main = "Color labels \nper cluster")
abline(h = 2, lty = 2)


dend %>% set("nodes_pch", 19) %>%  # node point type
  set("nodes_cex", 2) %>%  # node point size
  set("nodes_col", "blue") %>% # node point color
  plot(main = "Node points")

dend %>% set("leaves_pch", 19) %>%  # node point type
  set("leaves_cex", 2) %>%  # node point size
  set("leaves_col", "blue") %>% # node point color
  plot(main = "Leaves points")

dend %>% set("leaves_pch", c(17, 18, 19)) %>%  # node point type
  set("leaves_cex", 2) %>%  # node point size
  set("leaves_col", c("blue", "red", "green")) %>% #node point color
  plot(main = "Leaves points")

dend %>% set("branches_k_color", 
             value = c("red", "blue"), k = 2) %>% 
   plot(main = "Customized colors")


dend %>% set("branches_k_color", k = 3) %>% plot
dend %>% rect.dendrogram(k=3, border = 8, lty = 5, lwd = 2)



dend <- iris[1:30,-5] %>% scale %>% dist %>% 
   hclust %>% as.dendrogram %>%
   set("branches_k_color", k=3) %>% set("branches_lwd", 1.2) %>%
   set("labels_colors") %>% set("labels_cex", c(.9,1.2)) %>% 
   set("leaves_pch", 19) %>% set("leaves_col", c("blue", "red"))
# plot the dend in usual "base" plotting engine:
plot(dend)

ggd1 <- as.ggdend(dend)
ggplot(ggd1, theme = theme_minimal()) 


#Radial plot
ggplot(ggd1, labels = TRUE) + 
  scale_y_reverse(expand = c(0.2, 0)) +
  coord_polar(theta="x")

```

```{r}
#pvclust

library(pvclust)

data(lung)
set.seed(1234)
result <- pvclust(lung[1:100, 1:10], method.dist="cor", 
                  method.hclust="average", nboot=10)

plot(result)
pvrect(result)

result %>% as.dendrogram %>% 
  set("branches_k_color", k = 2, value = c("purple", "orange")) %>%
  plot
result %>% text
result %>% pvrect
```

